export default {
  START_GAME: 'START_GAME',
  UPDATE_HELICOPTER_TOP: 'UPDATE_HELICOPTER_TOP',
  UPDATE_BOMB_LEFT: 'UPDATE_BOMB_LEFT',
  GENERATE_BOMBS: 'GENERATE_BOMB',
  INIT_GAME: 'INIT_GAME',
  INIT_RECORD: 'INIT_RECORD',
  UPDATE_SCORE: 'UPDATE_SCORE',
};
